project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  author: "Matt Jones, Bryce Mecum, Jeanette Clark, Sam Csik"
  date: "September 19, 2022"
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://arcticdata.io
      - icon: twitter
        href: https://twitter.com/arcticdatactr
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course

  chapters:
    - index.qmd
    - 01-adc-intro.qmd
    - 02-remote-computing.qmd
    - 03-python-intro.qmd
    - 04-parallel-programming.qmd
    - 05-adc-data-publishing.qmd
    - 06-group-project-1.qmd
    - 07-software-design-1.qmd
    - 08-data-structures-netcdf.qmd
    - 09-parallel-with-dask.qmd
    - 10-geopandas.qmd
    - 11-parquet-arrow.qmd
    - 12-software-design-2.qmd
    - 13-group-project-2.qmd
    - 14-data-ethics.qmd
    - 15-google-earth-engine.qmd
    - 17-group-project-3.qmd
    - 18-arctic-data-staging.qmd
    - 19-cloud-computing.qmd
    - 20-reproducibility-containers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



