project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  doi: 10.18739/A2QF8JM2V
  author: "S. Jeanette Clark, Matthew B. Jones, Samantha Csik, Carmen Galaz García, Bryce Mecum, Natasha Haycock-Chavez, Daphne Virlar-Knight, Juliet Cohen, Anna Liljedahl"
  date: "March 25, 2024"
  issued: 2024
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://arcticdata.io
      - icon: twitter
        href: https://twitter.com/arcticdatactr
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course

  chapters:
    - index.qmd
    - sections/adc-intro.qmd
    - sections/remote-computing.qmd
    - sections/python-intro.qmd
    - sections/parallel-programming.qmd
    - sections/data-structures-netcdf.qmd
    - sections/parallel-with-dask.qmd
    - sections/group-project-1.qmd
    - sections/data-ethics.qmd
    - sections/geopandas.qmd
    - sections/geoscience-and-ai.qmd
    - sections/group-project-2.qmd
    - sections/software-design-1.qmd
    - sections/adc-data-publishing.qmd
    - sections/zarr.qmd
    - sections/docker-containers.qmd
    - sections/software-design-2.qmd
    - sections/docker-hpc-cloud.qmd
    - sections/reproducibility-containers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    



