project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  author: "Matt Jones, Bryce Mecum, Jeanette Clark, Sam Csik"
  date: "September 19-23, 2022"
  chapters:
    - index.qmd
    - sections/01-adc-intro.qmd
    - sections/02-remote-computing.qmd
    - sections/03-python-intro.qmd
    - sections/04-parallel-programming.qmd
    - sections/05-adc-data-publishing.qmd
    - sections/referenes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



