project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  author: "S. Jeanette Clark, Matthew B. Jones, Samantha Csik, Carmen Galaz García, Bryce Mecum, Natasha Haycock-Chavez, Daphne Virlar-Knight, Ingmar Nitze, Chandi Witharana"
  date: "September 19, 2022"
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://arcticdata.io
      - icon: twitter
        href: https://twitter.com/arcticdatactr
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course

  chapters:
    - index.qmd
    - sections/01-adc-intro.qmd
    - sections/02-remote-computing.qmd
    - sections/03-python-intro.qmd
    - sections/04-parallel-programming.qmd
    - sections/05-adc-data-publishing.qmd
    - sections/06-group-project-1.qmd
    - sections/07-software-design-1.qmd
    - sections/08-data-structures-netcdf.qmd
    - sections/09-parallel-with-dask.qmd
    - sections/10-geopandas.qmd
    - sections/11-parquet-arrow.qmd
    - sections/12-software-design-2.qmd
    - sections/13-group-project-2.qmd
    - sections/14-data-ethics.qmd
    - sections/15-google-earth-engine.qmd
    - sections/16-ice-wedge-polygons.qmd
    - sections/17-group-project-3.qmd
    - sections/18-arctic-data-staging.qmd
    - sections/19-cloud-computing.qmd
    - sections/20-reproducibility-containers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt



