project:
  type: book

book:
  title: "Quick review: remote computing"
  author: "Matthew B. Jones"
  date: "May 7, 2026"
  issued: 2026
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://nceas.ucsb.edu
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course
  chapters:
    - index.qmd
    - sections/remote-computing.qmd
    - sections/parallel-programming.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    



