project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  author: "S. Jeanette Clark, Juliet Cohen, Matthew B. Jones, Anna Liljedahl, Daphne Virlar-Knight"
  date: "March 27, 2023"
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://arcticdata.io
      - icon: twitter
        href: https://twitter.com/arcticdatactr
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course

  chapters:
    - index.qmd
    - sections/adc-intro.qmd
    - sections/remote-computing.qmd
    - sections/python-intro.qmd
    - sections/parallel-programming.qmd
    - sections/data-structures-netcdf.qmd
    - sections/parallel-with-dask.qmd
    - sections/group-project-1.qmd
    - sections/software-design-1.qmd
    - sections/geopandas.qmd
    - sections/ice-wedge-polygons.qmd
    - sections/group-project-2.qmd
    - sections/data-ethics.qmd
    - sections/google-earth-engine.qmd
    - sections/adc-data-publishing.qmd
    - sections/group-project-3.qmd
    - sections/software-design-2.qmd
    - sections/cloud-computing.qmd
    - sections/reproducibility-containers.qmd
    - sections/parquet-arrow.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    



