project:
  type: book

book:
  title: "Scalable and Computationally Reproducible Approaches to Arctic Research"
  author: "Matt Jones, Bryce Mecum, Jeanette Clark, Sam Csik"
  date: "September 19, 2022"
  reader-mode: false
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: false
    tools:
      - icon: house-door-fill
        href: https://arcticdata.io
      - icon: twitter
        href: https://twitter.com/arcticdatactr
      - icon: github
        href: https://github.com/NCEAS/scalable-computing-course

  chapters:
    - index.qmd
    - sections/01-adc-intro.qmd
    - sections/02-remote-computing.qmd
    - sections/03-python-intro.qmd
    - sections/04-parallel-programming.qmd
    - sections/05-adc-data-publishing.qmd
    - sections/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



